### PR TITLE
Updated readme on how to test dioxus with local crate.

### PR DESCRIPTION
**Pull request by bunnyBites**
Add readme on how to run or test dioxus with their local crate. This section will help devs who want to test the feature they are working with with their local rust bin project (crate).

### CODE REVIEW

**Review by ealmloff — APPROVED** [review]
Thank you!

**Comment by bunnyBites** [comment]
> Thank you!

It seems like it was written by. Sorry for making you do so 😅😅. I should be the one thanking you 😁.

**Comment by ealmloff** [comment]
Overall your original version was good, I just noticed a few things small things that I have learned people have issues with in the past. They were easy enough to fix while I was reviewing this 🙂:
1) Some people don't like comments in commands because they can't copy paste the command depending on the system
2) If you mention something about do x for y platform, some people will assume that the process if different on other platforms

**Comment by bunnyBites** [comment]
@ealmloff I totally agree, that really makes sense 🧠.  I will keep that in mind for the next time 🤓. Seriously man, thanks for sharing these insights 😊. Respect ++.

**Pull request merged**
