### PR TITLE
Rewrite Docs with new router

### PR DESCRIPTION
**Pull request by Demonthos**
This is built on top of #63 and https://github.com/DioxusLabs/dioxus/pull/1020 and https://github.com/Demonthos/include_mdbook/tree/router-intigration.

Docs outline:
https://excalidraw.com/#room=d8e228990924048be951,MBE9NeSUUezwjkfPMyIv_A

closes https://github.com/DioxusLabs/dioxus/issues/964
closes https://github.com/DioxusLabs/dioxus/issues/955
closes https://github.com/DioxusLabs/dioxus/issues/622

### CODE REVIEW

**Comment by Demonthos** [comment]
Some issues other people noticed:
- [ ] ctrl+k opens navbar on chrome
- [ ] all the blog post links are broken
- [ ] Panic on
1. Click "Get Started"
2. Click back arrow
3. Click forward arrow

**Comment by stephenandary** [comment]
Typo @ /docsite/learn/CLI/configure#webapp- : `configeration`

**Comment by stephenandary** [comment]
I have caught a few things like this now, and it makes me wonder what best way to lint for spelling is? I hit this type of stuff all the time too, and it is pretty much unavoidable in the writing process. 

I have tried a vscode extension for markdown, but maybe there is a GH action or lint one can do that hits it with spellcheck or Grammarly or something?

**Comment by stephenandary** [comment]
Also, I think I saw that this was fixed in Discord: 
image

Should I be loading this documentation for a different URL now?

**Comment by stephenandary** [comment]
Also noticing that the footer may not be a nice experience when scrolling the doc. May be worth rethinking how the footer is included.

**Comment by jkelleyrtp** [comment]
The links that I added that don't work / need updating:
- quickstart doesn't point to anything yet
- read the docs doesn't point to anything yet
- deploy page needs to be added / point to a typeform / point to notion
- the "get started" button with ferris at the bottom points to 0.3 and needs to point to 0.4

**Comment by jkelleyrtp** [comment]
ggreaat ty

**Pull request merged**
